package Vistas;

import DAO.AsistenciaDAO;
import java.sql.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AsistenciaPersonal extends javax.swing.JFrame {

    private AsistenciaDAO asistenciaDAO;
    private DefaultTableModel modeloTabla;
    
    public AsistenciaPersonal() {
        initComponents();
        this.setLocationRelativeTo(null);
        asistenciaDAO = new AsistenciaDAO();
        inicializarTabla();
        inicializarComponentes();
        cargarDatos();
    }
    
    private void inicializarComponentes() {
        // Configurar fecha actual en el spinner
        jSpinnerFecha.setValue(new java.util.Date());
    }
    
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"DNI", "Nombres", "Apellidos", "Cargo", "Estado"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table_personal.setModel(modeloTabla);
    }
    
    private void cargarDatos() {
        limpiarTabla();
        
        // Obtener fecha seleccionada
        java.util.Date fechaUtil = (java.util.Date) jSpinnerFecha.getValue();
        Date fechaSQL = new Date(fechaUtil.getTime());
        
        // Obtener personal con asistencia
        List<Map<String, Object>> lista = asistenciaDAO.obtenerPersonalConAsistencia(fechaSQL);
        
        for (Map<String, Object> fila : lista) {
            Object[] datos = {
                fila.get("dni"),
                fila.get("nombres"),
                fila.get("apellidos"),
                fila.get("cargo"),
                fila.get("estado")
            };
            modeloTabla.addRow(datos);
        }
    }
    
    private void limpiarTabla() {
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }
    
    private void marcarAsistencia(String estadoAsistencia) {
        int filaSeleccionada = table_personal.getSelectedRow();
        
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, 
                "Seleccione un personal de la tabla", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Obtener DNI del personal seleccionado
            String dni = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
            
            // Obtener ID del personal desde la base de datos
            int idPersonal = obtenerIdPersonalPorDNI(dni);
            
            if (idPersonal == -1) {
                JOptionPane.showMessageDialog(this, 
                    "No se pudo obtener el ID del personal", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Obtener fecha seleccionada
            java.util.Date fechaUtil = (java.util.Date) jSpinnerFecha.getValue();
            Date fechaSQL = new Date(fechaUtil.getTime());
            
            // Registrar asistencia
            if (asistenciaDAO.registrarAsistenciaPersonal(idPersonal, fechaSQL, estadoAsistencia)) {
                JOptionPane.showMessageDialog(this, 
                    "Asistencia marcada como: " + estadoAsistencia, 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                cargarDatos(); // Recargar la tabla
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Error al registrar asistencia", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private int obtenerIdPersonalPorDNI(String dni) {
        // Buscar el ID en la lista actual
        List<Map<String, Object>> lista = asistenciaDAO.obtenerPersonalConAsistencia(
            new Date(((java.util.Date) jSpinnerFecha.getValue()).getTime())
        );
        
        for (Map<String, Object> fila : lista) {
            if (fila.get("dni").toString().equals(dni)) {
                return (int) fila.get("id_personal");
            }
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuAsistencia = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_personal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        btnMarcarTardanza = new javax.swing.JButton();
        btnMarcarAsistencia = new javax.swing.JButton();
        btnMarcarFalta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("ASISTENCIA DE PERSONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 640, 80));

        btnMenuAsistencia.setBackground(new java.awt.Color(181, 181, 181));
        btnMenuAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_menu_80.png"))); // NOI18N
        btnMenuAsistencia.setBorder(null);
        btnMenuAsistencia.setOpaque(true);
        btnMenuAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_limpieza80.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_limpieza80.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        table_personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "DNI", "Cargo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(table_personal);
        if (table_personal.getColumnModel().getColumnCount() > 0) {
            table_personal.getColumnModel().getColumn(0).setResizable(false);
            table_personal.getColumnModel().getColumn(1).setResizable(false);
            table_personal.getColumnModel().getColumn(2).setResizable(false);
            table_personal.getColumnModel().getColumn(3).setResizable(false);
            table_personal.getColumnModel().getColumn(4).setResizable(false);
            table_personal.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 950, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Buscar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 40));

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFecha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerFechaStateChanged(evt);
            }
        });
        getContentPane().add(jSpinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        btnMarcarTardanza.setBackground(new java.awt.Color(255, 204, 51));
        btnMarcarTardanza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarTardanza.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarTardanza.setText("Marcar Tardanza");
        btnMarcarTardanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarTardanzaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcarTardanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 160, 50));

        btnMarcarAsistencia.setBackground(new java.awt.Color(51, 204, 0));
        btnMarcarAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarAsistencia.setText("Marcar Asistencia");
        btnMarcarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarAsistenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 160, 50));

        btnMarcarFalta.setBackground(new java.awt.Color(255, 51, 51));
        btnMarcarFalta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarcarFalta.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarFalta.setText("Marcar Falta");
        btnMarcarFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarFaltaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcarFalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 160, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 270, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAsistenciaActionPerformed
        VistaMenuPrincipal menu = new VistaMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnMenuAsistenciaActionPerformed

    private void btnMarcarTardanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarTardanzaActionPerformed
        marcarAsistencia("Tardanza");
    }//GEN-LAST:event_btnMarcarTardanzaActionPerformed

    private void btnMarcarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarAsistenciaActionPerformed
        marcarAsistencia("Presente");
    }//GEN-LAST:event_btnMarcarAsistenciaActionPerformed

    private void btnMarcarFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarFaltaActionPerformed
        marcarAsistencia("Ausente");
    }//GEN-LAST:event_btnMarcarFaltaActionPerformed

    private void jSpinnerFechaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerFechaStateChanged
        cargarDatos();
    }//GEN-LAST:event_jSpinnerFechaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenciaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenciaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenciaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenciaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciaPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarAsistencia;
    private javax.swing.JButton btnMarcarFalta;
    private javax.swing.JButton btnMarcarTardanza;
    private javax.swing.JButton btnMenuAsistencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table_personal;
    // End of variables declaration//GEN-END:variables
}
