
package Vistas;


public class VistaRegistroEstudiantes extends javax.swing.JFrame {


    public VistaRegistroEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuEstudiante = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAula = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtGrado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnNuevoEstudiante = new javax.swing.JButton();
        btnModificarEstudiante = new javax.swing.JButton();
        btnLimpiarEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("REGISTRO DE ESTUDIANTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 640, 70));

        btnMenuEstudiante.setBackground(new java.awt.Color(181, 181, 181));
        btnMenuEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_menu_80.png"))); // NOI18N
        btnMenuEstudiante.setBorder(null);
        btnMenuEstudiante.setOpaque(true);
        btnMenuEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_iestpvillamaria_80.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Apellidos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Carrera:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ciclo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        txtAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 180, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 180, -1));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 180, -1));

        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 180, -1));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 180, -1));

        txtGrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 180, -1));

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Nombres", "Apellidos", "Carrera", "Ciclo"
            }
        ));
        jScrollPane1.setViewportView(tablaEstudiantes);
        if (tablaEstudiantes.getColumnModel().getColumnCount() > 0) {
            tablaEstudiantes.getColumnModel().getColumn(2).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(3).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 960, 300));

        btnNuevoEstudiante.setBackground(new java.awt.Color(0, 153, 51));
        btnNuevoEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEstudiante.setText("Nuevo...");
        btnNuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 120, 40));

        btnModificarEstudiante.setBackground(new java.awt.Color(255, 204, 51));
        btnModificarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarEstudiante.setText("Modificar");
        btnModificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 120, 40));

        btnLimpiarEstudiante.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpiarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarEstudiante.setText("Limpiar");
        getContentPane().add(btnLimpiarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 120, 40));

        btnEliminarEstudiante.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEstudiante.setText("Eliminar");
        getContentPane().add(btnEliminarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 120, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiantesregistro_210.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoEstudianteActionPerformed

    private void btnModificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarEstudianteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnMenuEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEstudianteActionPerformed
        VistaMenuPrincipal menu = new VistaMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_btnMenuEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnLimpiarEstudiante;
    private javax.swing.JButton btnMenuEstudiante;
    private javax.swing.JButton btnModificarEstudiante;
    private javax.swing.JButton btnNuevoEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
