/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author IESTP VM
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegistroEstudiantes = new javax.swing.JButton();
        btnRegistroPersonal = new javax.swing.JButton();
        btnAsistenciaPersonal1 = new javax.swing.JButton();
        btnAsistenciaEstudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(181, 181, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 54)); // NOI18N
        jLabel1.setText("MENÚ DE OPCIONES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 540, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 204, 102));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarsesion_menu_80.png"))); // NOI18N
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 80, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_iestpvillamaria_80.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 100));

        btnRegistroEstudiantes.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistroEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnRegistroEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante_boton_100.png"))); // NOI18N
        btnRegistroEstudiantes.setText("<html>REGISTRO DE <br>ESTUDIANTES");
        btnRegistroEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 350, 180));

        btnRegistroPersonal.setBackground(new java.awt.Color(255, 255, 153));
        btnRegistroPersonal.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnRegistroPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profesor_boton_100.png"))); // NOI18N
        btnRegistroPersonal.setText("<html> REGISTRO DE <br> PERSONAL");
        btnRegistroPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 350, 180));

        btnAsistenciaPersonal1.setBackground(new java.awt.Color(255, 153, 153));
        btnAsistenciaPersonal1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnAsistenciaPersonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes_boton_100.png"))); // NOI18N
        btnAsistenciaPersonal1.setText("<html>ASISTENCIA <br>PERSONAL");
        btnAsistenciaPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaPersonal1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsistenciaPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 350, 180));

        btnAsistenciaEstudiantes.setBackground(new java.awt.Color(153, 255, 153));
        btnAsistenciaEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnAsistenciaEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asistencia_boton_90.png"))); // NOI18N
        btnAsistenciaEstudiantes.setText("<html>ASISTENCIA<br>  ESTUDIANTES");
        btnAsistenciaEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsistenciaEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 350, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEstudiantesActionPerformed
        VistaRegistroEstudiantes vistaEstudiantes = new VistaRegistroEstudiantes();
        vistaEstudiantes.setVisible(true);
        vistaEstudiantes.setLocationRelativeTo(null); // Centrar ventana
        this.dispose();  
    }//GEN-LAST:event_btnRegistroEstudiantesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro que desea cerrar sesión?",
            "Confirmar cierre de sesión",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            VistaLogin login = new VistaLogin();
            login.setVisible(true);
            login.setLocationRelativeTo(null); 
            this.dispose(); 
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRegistroPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPersonalActionPerformed
        VistaRegistroPersonal vistaPersonal = new VistaRegistroPersonal();
        vistaPersonal.setVisible(true);
        vistaPersonal.setLocationRelativeTo(null); // Centrar ventana
        this.dispose();
    }//GEN-LAST:event_btnRegistroPersonalActionPerformed

    private void btnAsistenciaPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaPersonal1ActionPerformed
        AsistenciaPersonal asistenciaPersonal = new AsistenciaPersonal();
        asistenciaPersonal.setVisible(true);
        asistenciaPersonal.setLocationRelativeTo(null); // Centrar ventana
        this.dispose();
    }//GEN-LAST:event_btnAsistenciaPersonal1ActionPerformed

    private void btnAsistenciaEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaEstudiantesActionPerformed
        AsistenciaEstudiantes asistenciaEstudiante = new AsistenciaEstudiantes();
        asistenciaEstudiante.setVisible(true);
        asistenciaEstudiante.setLocationRelativeTo(null); // Centrar ventana
        this.dispose();
    }//GEN-LAST:event_btnAsistenciaEstudiantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistenciaEstudiantes;
    private javax.swing.JButton btnAsistenciaPersonal1;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRegistroEstudiantes;
    private javax.swing.JButton btnRegistroPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
