
package Vistas;
import DAO.EstudianteDAO;
import Modelo.Estudiante;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaRegistroEstudiantes extends javax.swing.JFrame {
    private EstudianteDAO estudianteDAO;
    private DefaultTableModel modeloTabla;
    
    public VistaRegistroEstudiantes() {
        initComponents();
        this.setLocationRelativeTo(null);
        estudianteDAO = new EstudianteDAO();
        inicializarTabla();
        cargarDatos();
        txtID.setEnabled(false); // El ID es autoincremental
    }
    
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"ID", "DNI", "Nombres", "Apellidos", "Carrera", "Ciclo", "Turno"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer tabla no editable
            }
        };
        tablaEstudiantes.setModel(modeloTabla);
    }
    
    
    private void cargarDatos() {
        limpiarTabla();
        List<Estudiante> lista = estudianteDAO.listarTodos();
        for (Estudiante est : lista) {
            Object[] fila = {
                est.getIdEstudiante(),
                est.getDni(),
                est.getNombres(),
                est.getApellidos(),
                est.getCarrera(),
                est.getCiclo(),
                est.getTurno()
            };
            modeloTabla.addRow(fila);
        }
    }
    
    private void limpiarTabla() {
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }
    
    private void limpiarCampos() {
        txtID.setText("");
        txtDNI.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        cmbCarrera.setSelectedIndex(0);
        cmbCiclo.setSelectedIndex(0);
        cmbTurno.setSelectedIndex(0);
        txtDNI.requestFocus();
    }
    
    private boolean validarCampos() {
        if (txtDNI.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDNI.requestFocus();
            return false;
        }
        if (txtDNI.getText().trim().length() != 8) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDNI.requestFocus();
            return false;
        }
        if (txtNombres.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los nombres", "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombres.requestFocus();
            return false;
        }
        if (txtApellidos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los apellidos", "Validación", JOptionPane.WARNING_MESSAGE);
            txtApellidos.requestFocus();
            return false;
        }
        return true;
    }
    
    private void cargarDatosEnCampos() {
        int filaSeleccionada = tablaEstudiantes.getSelectedRow();
        if (filaSeleccionada >= 0) {
            txtID.setText(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
            txtDNI.setText(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
            txtNombres.setText(modeloTabla.getValueAt(filaSeleccionada, 2).toString());
            txtApellidos.setText(modeloTabla.getValueAt(filaSeleccionada, 3).toString());
            cmbCarrera.setSelectedItem(modeloTabla.getValueAt(filaSeleccionada, 4).toString());
            cmbCiclo.setSelectedItem(modeloTabla.getValueAt(filaSeleccionada, 5).toString());
            cmbTurno.setSelectedItem(modeloTabla.getValueAt(filaSeleccionada, 6).toString());
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuEstudiante = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnNuevoEstudiante = new javax.swing.JButton();
        btnModificarEstudiante = new javax.swing.JButton();
        btnLimpiarEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        cmbTurno = new javax.swing.JComboBox<>();
        cmbCiclo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("REGISTRO DE ESTUDIANTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 640, 70));

        btnMenuEstudiante.setBackground(new java.awt.Color(181, 181, 181));
        btnMenuEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_menu_80.png"))); // NOI18N
        btnMenuEstudiante.setBorder(null);
        btnMenuEstudiante.setOpaque(true);
        btnMenuEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_iestpvillamaria_80.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Apellidos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Carrera:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Turno:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, -1));

        txtDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, -1));

        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 180, -1));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 180, -1));

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Nombres", "Apellidos", "Carrera", "Ciclo", "Turno"
            }
        ));
        tablaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);
        if (tablaEstudiantes.getColumnModel().getColumnCount() > 0) {
            tablaEstudiantes.getColumnModel().getColumn(0).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(1).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(2).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(3).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(4).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(5).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 960, 300));

        btnNuevoEstudiante.setBackground(new java.awt.Color(0, 153, 51));
        btnNuevoEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEstudiante.setText("Nuevo...");
        btnNuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 120, 40));

        btnModificarEstudiante.setBackground(new java.awt.Color(255, 204, 51));
        btnModificarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarEstudiante.setText("Modificar");
        btnModificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 120, 40));

        btnLimpiarEstudiante.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpiarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarEstudiante.setText("Limpiar");
        btnLimpiarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 120, 40));

        btnEliminarEstudiante.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEstudiante.setText("Eliminar");
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 120, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiantesregistro_210.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 250));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Ciclo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computación e Informática", "Enfermería Técnica", "Cosmética Dermatológica", "Industrias Alimentarias" }));
        getContentPane().add(cmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 180, 30));

        cmbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Noche" }));
        getContentPane().add(cmbTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 180, 30));

        cmbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V", "VI" }));
        getContentPane().add(cmbCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEstudianteActionPerformed
        if (!validarCampos()) return;
        
        Estudiante est = new Estudiante(
            txtDNI.getText().trim(),
            txtNombres.getText().trim(),
            txtApellidos.getText().trim(),
            cmbCarrera.getSelectedItem().toString(),
            cmbCiclo.getSelectedItem().toString(),
            cmbTurno.getSelectedItem().toString()
        );
        
        if (estudianteDAO.insertar(est)) {
            JOptionPane.showMessageDialog(this, "Estudiante registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarDatos();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar estudiante", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoEstudianteActionPerformed

    private void btnModificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEstudianteActionPerformed
        if (txtID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un estudiante de la tabla", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) return;
        
        Estudiante est = new Estudiante(
            Integer.parseInt(txtID.getText()),
            txtDNI.getText().trim(),
            txtNombres.getText().trim(),
            txtApellidos.getText().trim(),
            cmbCarrera.getSelectedItem().toString(),
            cmbCiclo.getSelectedItem().toString(),
            cmbTurno.getSelectedItem().toString(),
            "Activo"
        );
        
        if (estudianteDAO.actualizar(est)) {
            JOptionPane.showMessageDialog(this, "Estudiante actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarDatos();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar estudiante", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarEstudianteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnMenuEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEstudianteActionPerformed
        VistaMenuPrincipal menu = new VistaMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_btnMenuEstudianteActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        if (txtID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un estudiante de la tabla", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este estudiante?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtID.getText());
            if (estudianteDAO.eliminar(id)) {
                JOptionPane.showMessageDialog(this, "Estudiante eliminado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar estudiante", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void btnLimpiarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEstudianteActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarEstudianteActionPerformed

    private void tablaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiantesMouseClicked
       cargarDatosEnCampos();
    }//GEN-LAST:event_tablaEstudiantesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnLimpiarEstudiante;
    private javax.swing.JButton btnMenuEstudiante;
    private javax.swing.JButton btnModificarEstudiante;
    private javax.swing.JButton btnNuevoEstudiante;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbCiclo;
    private javax.swing.JComboBox<String> cmbTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
