
package Vistas;


public class VistaRegistroPersonal extends javax.swing.JFrame {


    public VistaRegistroPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuPersonal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        txtIDPersonal = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonal = new javax.swing.JTable();
        btnNuevoPersonal = new javax.swing.JButton();
        btnModificarPersonal = new javax.swing.JButton();
        btnLimpiarPersonal = new javax.swing.JButton();
        btnEliminarPersonal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("REGISTRO DE PERSONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 640, 70));

        btnMenuPersonal.setBackground(new java.awt.Color(181, 181, 181));
        btnMenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_menu_80.png"))); // NOI18N
        btnMenuPersonal.setBorder(null);
        btnMenuPersonal.setOpaque(true);
        btnMenuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 80, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_iestpvillamaria_80.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Cargo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        txtCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 180, -1));

        txtIDPersonal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 180, -1));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 180, -1));

        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 180, -1));

        txtDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 180, -1));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 180, -1));

        tablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Nombres", "Apellidos", "Correo", "Telefono", "Cargo", "Horario"
            }
        ));
        jScrollPane1.setViewportView(tablaPersonal);
        if (tablaPersonal.getColumnModel().getColumnCount() > 0) {
            tablaPersonal.getColumnModel().getColumn(0).setResizable(false);
            tablaPersonal.getColumnModel().getColumn(1).setResizable(false);
            tablaPersonal.getColumnModel().getColumn(3).setResizable(false);
            tablaPersonal.getColumnModel().getColumn(4).setResizable(false);
            tablaPersonal.getColumnModel().getColumn(6).setResizable(false);
            tablaPersonal.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 377, 960, 300));

        btnNuevoPersonal.setBackground(new java.awt.Color(0, 153, 51));
        btnNuevoPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPersonal.setText("Nuevo...");
        btnNuevoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 127, 120, 40));

        btnModificarPersonal.setBackground(new java.awt.Color(255, 204, 51));
        btnModificarPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPersonal.setText("Modificar");
        btnModificarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 187, 120, 40));

        btnLimpiarPersonal.setBackground(new java.awt.Color(102, 102, 255));
        btnLimpiarPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarPersonal.setText("Limpiar");
        getContentPane().add(btnLimpiarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 307, 120, 40));

        btnEliminarPersonal.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPersonal.setText("Eliminar");
        getContentPane().add(btnEliminarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 247, 120, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 117, 200, 250));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Apellidos:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 180, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Horario:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        txtHorario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPersonalActionPerformed
        VistaMenuPrincipal menu = new VistaMenuPrincipal();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnMenuPersonalActionPerformed

    private void txtIDPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPersonalActionPerformed

    private void btnNuevoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPersonalActionPerformed

    private void btnModificarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPersonal;
    private javax.swing.JButton btnLimpiarPersonal;
    private javax.swing.JButton btnMenuPersonal;
    private javax.swing.JButton btnModificarPersonal;
    private javax.swing.JButton btnNuevoPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPersonal;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtIDPersonal;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
